import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import pg from 'pg';
import { addAssetVersion } from '../src/modules/admin/assets/service.js';
import { createBomImport, createOrReplaceBomFromImport, getBom, submitBomVerification, updateBomItems, updateBomUnitRules } from '../src/modules/admin/bill-of-materials/service.js';

test('BOM transactions preserve baseline, idempotency, rule identity and publication state', { skip: !process.env.BOM_TEST_DATABASE_URL }, async t => {
  const pool = new pg.Pool({connectionString:process.env.BOM_TEST_DATABASE_URL});
  const code = `bom-test-${randomUUID()}`;
  const secondCode = `bom-test-${randomUUID()}`;
  const adminId = randomUUID();
  const model = randomUUID();
  const scheme = randomUUID();
  const second = randomUUID();
  t.after(async () => {
    await pool.query('DELETE FROM schemes WHERE id = ANY($1::uuid[])',[ [scheme,second] ]);
    await pool.query('DELETE FROM admins WHERE id=$1',[adminId]);
    await pool.end();
  });
  await pool.query("INSERT INTO admins (id,external_user_id,username,roles,permissions) VALUES ($1,$2,$3,ARRAY['ROLE_ADMIN'],ARRAY['scheme.read','scheme.edit','scheme.import','scheme.review'])",[adminId,Math.floor(Math.random()*1e12),code]);
  await pool.query("INSERT INTO schemes (id,code,name,publish_status) VALUES ($1,$2,$3,'published'),($4,$5,$6,'draft')",[scheme,code,code,second,secondCode,secondCode]);
  const preview = { items:[{ productName:'杆件',sourceQuantity:'2500',sourceUnit:'mm' },{ productName:'组件',sourceQuantity:'4',sourceUnit:'个' }],unitRules:[{measurementKind:'length' as const,sourceUnit:'mm',pricingUnit:'m',conversionCode:'mm_to_m' as const},{measurementKind:'count' as const,sourceUnit:'个',pricingUnit:'个',conversionCode:'identity' as const}],errors:[],warnings:[{code:'SCHEME_CODE_MISSING_IN_SOURCE',message:'确认归属'}] };
  const createImport = async (hash: string, revision: number) => {
    const objectKey=`tests/${randomUUID()}.xlsx`;
    return createBomImport(pool,adminId,code,'test.xlsx',hash,objectKey,10,revision,preview);
  };
  const imported = await createImport('hash',0);
  await assert.rejects(createOrReplaceBomFromImport(pool,adminId,code,imported.id,1,['SCHEME_CODE_MISSING_IN_SOURCE'],'导入'),{reason:'BOM_REVISION_CHANGED'});
  await assert.rejects(createOrReplaceBomFromImport(pool,adminId,code,imported.id,0,[],'导入'),{reason:'WARNINGS_UNCONFIRMED'});
  const original = await createOrReplaceBomFromImport(pool,adminId,code,imported.id,0,['SCHEME_CODE_MISSING_IN_SOURCE'],'导入');
  assert.deepEqual([original.revision,original.itemCount,original.unpublished],[1,2,true]);
  let bom = (await getBom(pool,code))!;
  assert.deepEqual(bom.items.map(item=>item.quantity),['2.500000','4.000000']);
  const rule = bom.unitRules.find(rule=>rule.sourceUnit==='mm')!;
  bom = await updateBomUnitRules(pool,adminId,code,1,'确认换算',bom.unitRules.map(value=>({id:value.id,measurementKind:value.measurementKind,sourceUnit:value.sourceUnit,pricingUnit:value.pricingUnit,conversionCode:value.conversionCode})));
  assert.equal(bom.items[0]?.unitRuleId,rule.id);
  await assert.rejects(updateBomUnitRules(pool,adminId,code,2,'删除引用规则',bom.unitRules.filter(value=>value.id!==rule.id)),{reason:'UNIT_RULE_INVALID'});
  assert.deepEqual(await createOrReplaceBomFromImport(pool,adminId,code,imported.id,0,['SCHEME_CODE_MISSING_IN_SOURCE'],'导入'),original);
  await assert.rejects(createOrReplaceBomFromImport(pool,adminId,code,imported.id,0,['SCHEME_CODE_MISSING_IN_SOURCE'],'另一原因'),{reason:'IDEMPOTENCY_CONFLICT'});
  const stale = await createImport('hash2',2);
  bom = await updateBomItems(pool,adminId,code,2,'修正条目',bom.items.map(item=>({id:item.id,productName:item.productName,sourceQuantity:item.sourceQuantity,sourceUnit:item.sourceUnit,unitRuleId:item.unitRuleId})));
  await assert.rejects(createOrReplaceBomFromImport(pool,adminId,code,stale.id,2,['SCHEME_CODE_MISSING_IN_SOURCE'],'旧预览'),{reason:'BOM_REVISION_CHANGED'});
  await pool.query("INSERT INTO scheme_assets (id,scheme_id,type,name) VALUES ($1,$2,'model','模型')",[model,scheme]);
  await pool.query("INSERT INTO asset_versions (asset_id,object_key,original_filename,mime_type,byte_size,checksum) VALUES ($1,$2,'model.skp','application/octet-stream',10,'modelhash')",[model,`tests/${randomUUID()}.skp`]);
  const input = {requestKey:randomUUID(),expectedRevision:bom.revision,decision:'pass' as const,checks:{sourceExtraction:true,modelCrossCheck:true,supportingParts:true,unitConsistency:true},modelAssetId:model,notes:'已核对'};
  const first = await submitBomVerification(pool,adminId,code,input);
  assert.equal(first.status,'verified');
  const replay = await submitBomVerification(pool,adminId,code,input);
  assert.deepEqual(replay,{...first,replayed:true});
  await addAssetVersion(pool,adminId,code,model,{objectKey:`tests/${randomUUID()}.skp`,originalFilename:'new.skp',mimeType:'application/octet-stream',byteSize:12,checksum:'newhash'},1);
  const invalidated = (await getBom(pool,code))!;
  assert.equal(invalidated.status,'pending_verification');
  assert.equal(invalidated.modelAssetVersionId,null);
  assert.equal(invalidated.revision,first.revision+1);
  await assert.rejects(submitBomVerification(pool,adminId,secondCode,input),{reason:'IDEMPOTENCY_CONFLICT'});
  await assert.rejects(submitBomVerification(pool,adminId,code,{...input,notes:'更改意见'}),{reason:'IDEMPOTENCY_CONFLICT'});
  const concurrent = await Promise.all([submitBomVerification(pool,adminId,code,{...input,requestKey:randomUUID(),expectedRevision:invalidated.revision,decision:'reject',notes:'不通过'}),submitBomVerification(pool,adminId,code,{...input,requestKey:randomUUID(),expectedRevision:invalidated.revision,decision:'reject',notes:'不通过'})].map(p=>p.then(()=>true,()=>false)));
  assert.deepEqual(concurrent.sort(),[false,true]);
});
