import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import pg from 'pg';
import Fastify from 'fastify';
import type { Redis } from 'ioredis';
import { createManualProject } from '../src/modules/projects/service.js';
import { assignProject,followUpProject,saveQuotation,quotationRevision } from '../src/modules/projects/admin-service.js';
import { getProject } from '../src/modules/projects/repository.js';
import { emptyRequirement } from '../src/modules/selection/domain.js';
import { registerClientProjectRoutes } from '../src/modules/client/projects/index.js';
import { registerAdminProjectRoutes } from '../src/modules/admin/projects/index.js';
import { registerClientManualRequestRoutes } from '../src/modules/client/manual-requests/index.js';
import type { createStorage } from '../src/infra/storage.js';
import type { ManualInput } from '../src/modules/projects/domain.js';
import type { QuotationInput } from '../src/modules/projects/quotation.js';

test('unified projects: manual acceptance, assignment, immutable quotation, state evidence and submitter isolation', {skip:!process.env.PROJECT_TEST_DATABASE_URL},async t=>{
  const pool=new pg.Pool({connectionString:process.env.PROJECT_TEST_DATABASE_URL});
  const admin=randomUUID();const secondAdmin=randomUUID();const user=randomUUID();const other=randomUUID();const ids:string[]=[];
  t.after(async()=>{
    await pool.query('DELETE FROM project_operations WHERE actor_id=ANY($1::uuid[])',[[admin,secondAdmin,user,other]]);
    await pool.query('DELETE FROM project_quotation_revisions WHERE project_id=ANY($1::uuid[])',[ids]);
    await pool.query('DELETE FROM project_notification_outbox WHERE project_id=ANY($1::uuid[])',[ids]);
    await pool.query('DELETE FROM project_events WHERE project_id=ANY($1::uuid[])',[ids]);
    await pool.query('DELETE FROM projects WHERE id=ANY($1::uuid[])',[ids]);
    await pool.query('DELETE FROM admins WHERE id=ANY($1::uuid[])',[[admin,secondAdmin]]);
    await pool.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[[user,other]]);await pool.end();
  });
  for(const id of [admin,secondAdmin])await pool.query("INSERT INTO admins(id,external_user_id,username,roles) VALUES($1::uuid,$2,$1::uuid::text,ARRAY['ROLE_ADMIN'])",[id,Math.floor(Math.random()*1e12)]);
  for(const id of [user,other])await pool.query('INSERT INTO users(id,external_user_id,username) VALUES($1::uuid,$2,$1::uuid::text)',[id,Math.floor(Math.random()*1e12)]);
  const input:ManualInput={requestKey:randomUUID(),entryPoint:'matching_results',originalDescription:'特殊尺寸，需要洽谈区',confirmedRequirements:emptyRequirement(),
    exhibition:{name:'集成验收展会',countryCode:'CN',city:'上海',startDate:'2026-11-20',endDate:'2026-11-22'},scopeCodes:['materials'],materialBudget:{currency:'CNY',amount:'30000'},customerType:'individual',contact:{name:'验收客户',email:'integration@example.com'}};
  const results=await Promise.all([createManualProject(pool,user,input),createManualProject(pool,user,input)]);
  const id=String(results[0]!.receipt.projectId);ids.push(id);assert.equal(results[1]!.receipt.projectId,id);assert.equal(results.filter(result=>!result.replayed).length,1);
  let project=await getProject(pool,id);assert.equal(project.schemeCode,null);
  const assignment={requestKey:randomUUID(),expectedRevision:1,assigneeAdminId:secondAdmin,reason:'更换负责管理员'};
  const assignmentResults=await Promise.all([assignProject(pool,id,admin,assignment),assignProject(pool,id,admin,assignment)]);
  assert.equal(assignmentResults[0]!.revision,2);assert.deepEqual(assignmentResults[0],assignmentResults[1]);
  await assert.rejects(assignProject(pool,id,admin,{...assignment,requestKey:randomUUID()}),{reason:'PROJECT_REVISION_CHANGED'});
  const follow=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:2,contactMethod:'email',contactedAt:new Date().toISOString(),content:'内部备注，不能返回客户端',targetStatus:'following'});
  assert.equal(follow.revision,3);
  const quote:QuotationInput={requestKey:randomUUID(),expectedRevision:3,expectedQuotationRevision:0,currency:'CNY',priceBasis:'excluded',validUntil:'2099-12-31',validityTimeZone:'Asia/Shanghai',
    items:[{clientLineId:'service',kind:'other',name:'测试服务',quantity:'3',pricingUnit:'项',unitPrice:'0.335'}],terms:'税费另行确认',inclusions:'测试服务',exclusions:'运输与搭建',changeReason:'首次录价'};
  const saved=await saveQuotation(pool,id,admin,quote);assert.equal(saved.quotation.totalAmount,'1.01');assert.equal(saved.projectRevision,4);
  assert.deepEqual(await saveQuotation(pool,id,admin,quote),saved);
  assert.equal((await getProject(pool,id)).status,'following');
  const second=await saveQuotation(pool,id,admin,{...quote,requestKey:randomUUID(),expectedRevision:4,expectedQuotationRevision:1,items:[{...quote.items[0]!,unitPrice:null}],changeReason:'待沟通草稿'});
  assert.equal(second.quotation.totalAmount,null);assert.equal((await quotationRevision(pool,id,1))?.totalAmount,'1.01');
  await assert.rejects(saveQuotation(pool,id,admin,{...quote,requestKey:randomUUID(),expectedRevision:5,expectedQuotationRevision:1}),{reason:'QUOTATION_REVISION_CHANGED'});
  await assert.rejects(followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:5,contactMethod:'email',contactedAt:new Date().toISOString(),content:'无发送证据',targetStatus:'quoted'}),{reason:'QUOTE_EVIDENCE_REQUIRED'});
  const sent=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:5,contactMethod:'email',contactedAt:new Date().toISOString(),content:'已发送历史完整修订',targetStatus:'quoted',
    quoteEvidence:{type:'platform',quotationRevision:1,sentAt:new Date().toISOString(),channel:'email'}});
  assert.equal(sent.revision,6);
  const won=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:6,contactMethod:'meeting',contactedAt:new Date().toISOString(),content:'确认成交',targetStatus:'won',outcome:'接受方案与报价',publicResult:'已确认项目方案'});
  await assert.rejects(assignProject(pool,id,admin,{...assignment,requestKey:randomUUID(),expectedRevision:won.revision}),{reason:'INVALID_STATUS_TRANSITION'});
  await assert.rejects(saveQuotation(pool,id,admin,{...quote,requestKey:randomUUID(),expectedRevision:won.revision,expectedQuotationRevision:2}),{reason:'INVALID_STATUS_TRANSITION'});
  await assert.rejects(followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:won.revision,contactMethod:'email',contactedAt:new Date().toISOString(),content:'直接回到待跟进',targetStatus:'pending'}),{reason:'INVALID_STATUS_TRANSITION'});
  const reopened=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:won.revision,contactMethod:'email',contactedAt:new Date().toISOString(),content:'客户补充需求',targetStatus:'following',reopenReason:'客户追加服务需重新沟通'});
  assert.equal(reopened.status,'following');
  const sessions:Record<string,unknown>={client:{site:'client',localId:user,expiresAt:Math.floor(Date.now()/1000)+3600},other:{site:'client',localId:other,expiresAt:Math.floor(Date.now()/1000)+3600},admin:{site:'admin',localId:admin,expiresAt:Math.floor(Date.now()/1000)+3600}};
  let active='client';const redis={get:async()=>JSON.stringify(sessions[active]),del:async()=>1,eval:async()=>1} as unknown as Redis;
  const storage={signDownload:async()=>'/test-preview',signDownloadWithName:async()=>'/test-download'} as unknown as ReturnType<typeof createStorage>;
  const app=Fastify({ajv:{customOptions:{removeAdditional:false}}});t.after(()=>app.close());
  await registerClientProjectRoutes(app,pool,redis,storage);await registerClientManualRequestRoutes(app,pool,redis);
  await app.register(async adminRoutes=>registerAdminProjectRoutes(adminRoutes,pool,redis,storage),{prefix:'/admin'});
  const headers={authorization:'Bearer test-token'};
  const replay=await app.inject({method:'POST',url:'/manual-requests',headers,payload:input});assert.equal(replay.statusCode,200);assert.equal(replay.json().data.projectId,id);
  assert.equal((await app.inject({method:'POST',url:'/manual-requests',payload:input})).statusCode,401);
  const detail=await app.inject({url:`/me/projects/${id}`,headers});assert.equal(detail.statusCode,200);assert.equal(detail.json().data.publicResult,'已确认项目方案');
  for(const field of ['assigneeAdminId','assigneeName','quotation','createdBy','objectKey','events','内部备注'])assert.ok(!detail.body.includes(field),`Public response leaked ${field}`);
  const list=await app.inject({url:'/me/projects',headers});assert.equal(list.json().data.total,1);assert.equal(list.json().data.items[0].projectId,id);
  assert.equal((await app.inject({url:`/me/projects?customerUserId=${other}`,headers})).statusCode,400);
  active='other';assert.equal((await app.inject({url:`/me/projects/${id}`,headers})).statusCode,404);assert.equal((await app.inject({url:'/me/projects',headers})).json().data.total,0);
  assert.equal((await app.inject({url:`/admin/projects/${id}`,headers})).statusCode,401);
  active='admin';const download=await app.inject({url:`/admin/projects/${id}/quotation/download?revision=1`,headers});assert.equal(download.statusCode,200);assert.ok(download.rawPayload.length>100);
  assert.equal((await app.inject({url:`/admin/projects/${id}/quotation/download?revision=2`,headers})).statusCode,409);
  await pool.query('UPDATE admins SET enabled=false WHERE id=$1',[admin]);assert.equal((await app.inject({url:`/admin/projects/${id}`,headers})).statusCode,403);
  active='client';assert.equal((await app.inject({method:'POST',url:'/manual-requests',headers,payload:{...input,schemeCode:'forbidden'}})).statusCode,400);
  project=await getProject(pool,id);assert.equal(project.status,'following');assert.equal(project.revision,8);
});
