import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { projectTestPool } from '../helpers/project-fixtures.js';
import Fastify from 'fastify';
import type { Redis } from 'ioredis';
import { createManualProject } from '../../src/modules/projects/service.js';
import { assignProject,followUpProject,saveQuotation,quotationRevision } from '../../src/modules/projects/admin-service.js';
import { getProject } from '../../src/modules/projects/repository.js';
import { claimAnonymousProjects } from '../../src/modules/projects/claims.js';
import { claimReceiptEmails, completeReceiptEmail, failReceiptEmail, RECEIPT_EMAIL_DAILY_LIMIT_PER_RECIPIENT, releaseReceiptEmails } from '../../src/modules/projects/receipt-emails.js';
import { emptyRequirement } from '../../src/modules/selection/domain.js';
import { registerClientProjectRoutes } from '../../src/http/client/projects/index.js';
import { registerAuthentication } from '../../src/http/authentication.js';
import { registerAdminProjectRoutes } from '../../src/http/admin/projects/index.js';
import { registerClientManualRequestRoutes } from '../../src/http/client/manual-requests/index.js';
import type { createStorage } from '../../src/infra/storage.js';
import type { ManualInput } from '../../src/modules/projects/domain.js';
import type { QuotationInput } from '../../src/modules/projects/quotation.js';

test('unified projects: manual acceptance, assignment, immutable quotation, state evidence and submitter isolation', {skip:!process.env.PROJECT_TEST_DATABASE_URL},async t=>{
  const pool=await projectTestPool(t);
  const admin=randomUUID();const secondAdmin=randomUUID();const user=randomUUID();const other=randomUUID();const ids:string[]=[];
  for(const id of [admin,secondAdmin])await pool.query("INSERT INTO admins(id,external_user_id,username,roles) VALUES($1::uuid,$2,$1::uuid::text,ARRAY['ROLE_ADMIN'])",[id,Math.floor(Math.random()*1e12)]);
  await pool.query('UPDATE project_assignment_config SET default_assignee_admin_id=$1',[admin]);
  for(const id of [user,other])await pool.query('INSERT INTO users(id,external_user_id,username) VALUES($1::uuid,$2,$1::uuid::text)',[id,Math.floor(Math.random()*1e12)]);
  const input:ManualInput={requestKey:randomUUID(),entryPoint:'matching_results',originalDescription:'特殊尺寸，需要洽谈区',confirmedRequirements:emptyRequirement(),
    exhibition:{name:'集成验收展会',countryCode:'CN',city:'上海',startDate:'2026-11-20',endDate:'2026-11-22'},scopeCodes:['materials'],materialBudget:{currency:'CNY',amount:'30000'},customerType:'individual',contact:{name:'验收客户',email:'integration@example.com'}};
  const results=await Promise.all([createManualProject(pool,user,input),createManualProject(pool,user,input)]);
  const id=String(results[0]!.receipt.projectId);ids.push(id);assert.equal(results[1]!.receipt.projectId,id);assert.equal(results.filter(result=>!result.replayed).length,1);
  let project=await getProject(pool,id);assert.equal(project.schemeCode,null);
  const assignment={requestKey:randomUUID(),expectedRevision:1,assigneeAdminId:secondAdmin,reason:'更换负责管理员'};
  const assignmentResults=await Promise.all([assignProject(pool,id,admin,assignment),assignProject(pool,id,admin,assignment)]);
  assert.equal(assignmentResults[0]!.revision,2);assert.deepEqual(assignmentResults[0],assignmentResults[1]);
  await assert.rejects(assignProject(pool,id,admin,{...assignment,requestKey:randomUUID()}),{reason:'PROJECT_REVISION_CHANGED'});
  const follow=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:2,contactMethod:'email',contactedAt:new Date().toISOString(),content:'内部备注，不能返回客户端',targetStatus:'following'});
  assert.equal(follow.revision,3);
  const quote:QuotationInput={requestKey:randomUUID(),expectedRevision:3,expectedQuotationRevision:0,currency:'CNY',priceBasis:'excluded',validUntil:'2099-12-31',validityTimeZone:'Asia/Shanghai',
    items:[{clientLineId:'service',kind:'other',name:'测试服务',quantity:'3',pricingUnit:'项',unitPrice:'0.335'}],terms:'税费另行确认',inclusions:'测试服务',exclusions:'运输与搭建',changeReason:'首次录价'};
  const saved=await saveQuotation(pool,id,admin,quote);assert.equal(saved.quotation.totalAmount,'1.01');assert.equal(saved.projectRevision,4);
  assert.deepEqual(await saveQuotation(pool,id,admin,quote),saved);
  assert.equal((await getProject(pool,id)).status,'following');
  const second=await saveQuotation(pool,id,admin,{...quote,requestKey:randomUUID(),expectedRevision:4,expectedQuotationRevision:1,items:[{...quote.items[0]!,unitPrice:null}],changeReason:'待沟通草稿'});
  assert.equal(second.quotation.totalAmount,null);assert.equal((await quotationRevision(pool,id,1))?.totalAmount,'1.01');
  await assert.rejects(saveQuotation(pool,id,admin,{...quote,requestKey:randomUUID(),expectedRevision:5,expectedQuotationRevision:1}),{reason:'QUOTATION_REVISION_CHANGED'});
  await assert.rejects(followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:5,contactMethod:'email',contactedAt:new Date().toISOString(),content:'无发送证据',targetStatus:'quoted'}),{reason:'QUOTE_EVIDENCE_REQUIRED'});
  const sent=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:5,contactMethod:'email',contactedAt:new Date().toISOString(),content:'已发送历史完整修订',targetStatus:'quoted',
    quoteEvidence:{type:'platform',quotationRevision:1,sentAt:new Date().toISOString(),channel:'email'}});
  assert.equal(sent.revision,6);
  const won=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:6,contactMethod:'meeting',contactedAt:new Date().toISOString(),content:'确认成交',targetStatus:'won',outcome:'接受方案与报价',publicResult:'已确认项目方案'});
  await assert.rejects(assignProject(pool,id,admin,{...assignment,requestKey:randomUUID(),expectedRevision:won.revision}),{reason:'INVALID_STATUS_TRANSITION'});
  await assert.rejects(saveQuotation(pool,id,admin,{...quote,requestKey:randomUUID(),expectedRevision:won.revision,expectedQuotationRevision:2}),{reason:'INVALID_STATUS_TRANSITION'});
  await assert.rejects(followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:won.revision,contactMethod:'email',contactedAt:new Date().toISOString(),content:'直接回到待跟进',targetStatus:'pending'}),{reason:'INVALID_STATUS_TRANSITION'});
  const reopened=await followUpProject(pool,id,admin,{requestKey:randomUUID(),expectedRevision:won.revision,contactMethod:'email',contactedAt:new Date().toISOString(),content:'客户补充需求',targetStatus:'following',reopenReason:'客户追加服务需重新沟通'});
  assert.equal(reopened.status,'following');
  const sessions:Record<string,unknown>={client:{site:'client',localId:user,sessionVersion:1,expiresAt:Math.floor(Date.now()/1000)+3600},other:{site:'client',localId:other,sessionVersion:1,expiresAt:Math.floor(Date.now()/1000)+3600},admin:{site:'admin',localId:admin,sessionVersion:1,expiresAt:Math.floor(Date.now()/1000)+3600}};
  let active='client';const redis={get:async()=>JSON.stringify(sessions[active]),del:async()=>1,eval:async()=>1} as unknown as Redis;
  const storage={signDownload:async()=>'/test-preview',signDownloadWithName:async()=>'/test-download'} as unknown as ReturnType<typeof createStorage>;
  const app=Fastify({ajv:{customOptions:{removeAdditional:false}}});t.after(()=>app.close());
  await app.register(async clientRoutes=>{registerAuthentication(clientRoutes,pool,redis,'client');await registerClientProjectRoutes(clientRoutes,pool,redis,storage);await registerClientManualRequestRoutes(clientRoutes,pool,redis);});
  await app.register(async adminRoutes=>{registerAuthentication(adminRoutes,pool,redis,'admin');await registerAdminProjectRoutes(adminRoutes,pool,storage);},{prefix:'/admin'});
  const headers={authorization:'Bearer test-token'};
  const replay=await app.inject({method:'POST',url:'/manual-requests',headers,payload:input});assert.equal(replay.statusCode,200);assert.equal(replay.json().data.projectId,id);
  assert.equal((await app.inject({method:'POST',url:'/manual-requests',payload:{...input,contact:{name:'访客',phone:'+86 138 0000 0000'}}})).statusCode,400);
  const detail=await app.inject({url:`/me/projects/${id}`,headers});assert.equal(detail.statusCode,200);assert.equal(detail.json().data.publicResult,'已确认项目方案');
  for(const field of ['assigneeAdminId','assigneeName','quotation','createdBy','objectKey','events','内部备注'])assert.ok(!detail.body.includes(field),`Public response leaked ${field}`);
  const list=await app.inject({url:'/me/projects',headers});assert.equal(list.json().data.total,1);assert.equal(list.json().data.items[0].projectId,id);
  assert.equal((await app.inject({url:`/me/projects?customerUserId=${other}`,headers})).statusCode,400);
  active='other';assert.equal((await app.inject({url:`/me/projects/${id}`,headers})).statusCode,404);assert.equal((await app.inject({url:'/me/projects',headers})).json().data.total,0);
  assert.equal((await app.inject({url:`/admin/projects/${id}`,headers})).statusCode,401);
  active='admin';const download=await app.inject({url:`/admin/projects/${id}/quotation/download?revision=1`,headers});assert.equal(download.statusCode,200);assert.ok(download.rawPayload.length>100);
  assert.equal((await app.inject({url:`/admin/projects/${id}/quotation/download?revision=2`,headers})).statusCode,409);
  const adminDetail=(await app.inject({url:`/admin/projects/${id}`,headers})).json().data;
  assert.deepEqual(adminDetail.statusTransitions,['quoted','won','lost','closed']);assert.deepEqual(adminDetail.requirementOptionLabels,{});
  const assigned=adminDetail.events.find((event:{kind:string})=>event.kind==='assignment');
  assert.equal(assigned.assigneeName,secondAdmin);assert.equal(assigned.fromAssigneeName,admin);
  const timelineIds=Array.from({length:25},(_,n)=>`00000000-0000-4000-8000-${String(n+1).padStart(12,'0')}`);
  for(let n=0;n<timelineIds.length;n++)await pool.query(
    "INSERT INTO project_events(id,project_id,kind,payload,created_at) VALUES($1,$2,'follow-up',$3,'2099-01-01'::timestamptz+$4*interval '1 second')",
    [timelineIds[n],id,{content:`时间线记录 ${n+1}`},Math.floor(n/2)]);
  const fullDetail=await app.inject({url:`/admin/projects/${id}`,headers});assert.equal(fullDetail.statusCode,200);
  const fullEvents=fullDetail.json().data.events;
  assert.equal(fullEvents.length,adminDetail.events.length+25);
  assert.deepEqual(fullEvents.slice(0,25).map((event:{id:string})=>event.id),timelineIds.toReversed());
  const eventsResponse=await app.inject({url:`/admin/projects/${id}/events`,headers});assert.equal(eventsResponse.statusCode,200);
  assert.deepEqual(eventsResponse.json().data,fullEvents);
  assert.equal((await app.inject({url:`/admin/projects/${id}/events?page=2&pageSize=20`,headers})).statusCode,400);
  await pool.query('UPDATE admins SET enabled=false WHERE id=$1',[admin]);assert.equal((await app.inject({url:`/admin/projects/${id}`,headers})).statusCode,403);
  active='client';assert.equal((await app.inject({method:'POST',url:'/manual-requests',headers,payload:{...input,schemeCode:'forbidden'}})).statusCode,400);
  project=await getProject(pool,id);assert.equal(project.status,'following');assert.equal(project.revision,8);
});

test('anonymous manual requests stay unclaimed until a user with the verified contact email logs in', {skip:!process.env.PROJECT_TEST_DATABASE_URL},async t=>{
  const pool=await projectTestPool(t);
  const admin=randomUUID();const owner=randomUUID();const stranger=randomUUID();
  await pool.query("INSERT INTO admins(id,external_user_id,username,roles) VALUES($1::uuid,$2,$1::uuid::text,ARRAY['ROLE_ADMIN'])",[admin,Math.floor(Math.random()*1e12)]);
  await pool.query('UPDATE project_assignment_config SET default_assignee_admin_id=$1',[admin]);
  for(const id of [owner,stranger])await pool.query('INSERT INTO users(id,external_user_id,username) VALUES($1::uuid,$2,$1::uuid::text)',[id,Math.floor(Math.random()*1e12)]);
  const input:ManualInput={requestKey:randomUUID(),entryPoint:'matching_results',originalDescription:'访客提交的特殊需求',confirmedRequirements:emptyRequirement(),
    exhibition:{name:'访客展会',countryCode:'CN',city:'上海',startDate:'2026-11-20',endDate:'2026-11-22'},scopeCodes:['materials'],materialBudget:{currency:'CNY',amount:'20000'},customerType:'individual',contact:{name:'访客',email:'Visitor@Example.com'}};
  const results=await Promise.all([createManualProject(pool,null,input),createManualProject(pool,null,input)]);
  const id=String(results[0]!.receipt.projectId);assert.equal(results[1]!.receipt.projectId,id);assert.equal(results.filter(result=>!result.replayed).length,1);
  await assert.rejects(createManualProject(pool,null,{...input,notes:'改动后重放'}),{reason:'IDEMPOTENCY_CONFLICT'});
  await assert.rejects(createManualProject(pool,null,{...input,requestKey:randomUUID(),contact:{name:'访客',phone:'+86 138 0000 0000'}}),{reason:'CLAIM_EMAIL_REQUIRED'});
  assert.equal((await getProject(pool,id)).customerUserId,null);
  const sameKey=await createManualProject(pool,owner,input);assert.notEqual(sameKey.receipt.projectId,id);assert.equal(sameKey.replayed,false);
  assert.deepEqual(await claimAnonymousProjects(pool,stranger,'other@example.com'),[]);
  assert.deepEqual(await claimAnonymousProjects(pool,stranger,null),[]);
  assert.deepEqual(await claimAnonymousProjects(pool,owner,' visitor@example.COM '),[id]);
  assert.equal((await getProject(pool,id,owner)).projectId,id);
  assert.deepEqual(await claimAnonymousProjects(pool,stranger,'visitor@example.com'),[]);
  const events=(await pool.query<{kind:string;payload:{customerUserId:string}}>('SELECT kind,payload FROM project_events WHERE project_id=$1 ORDER BY created_at',[id])).rows;
  assert.deepEqual(events.map(event=>event.kind),['accepted','claimed']);assert.equal(events[1]!.payload.customerUserId,owner);
  const receipts=(await pool.query<{projectId:string;recipient:string;locale:string;accountBound:boolean}>('SELECT project_id AS "projectId",recipient,locale,account_bound AS "accountBound" FROM project_receipt_emails ORDER BY created_at')).rows;
  assert.deepEqual(receipts,[{projectId:id,recipient:'Visitor@Example.com',locale:'zh',accountBound:false},{projectId:sameKey.receipt.projectId,recipient:'Visitor@Example.com',locale:'zh',accountBound:true}]);
  for(let n=0;n<4;n++)await createManualProject(pool,null,{...input,requestKey:randomUUID(),contact:{name:'访客',email:'VISITOR@example.com'}},'en');
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM project_receipt_emails')).rows[0].count,RECEIPT_EMAIL_DAILY_LIMIT_PER_RECIPIENT);
  const claimed=await claimReceiptEmails(pool,2);assert.equal(claimed.length,2);assert.equal(claimed[0]!.projectNo,(await getProject(pool,id)).projectNo);assert.equal(claimed[0]!.contactName,'访客');assert.equal(claimed[0]!.exhibition?.name,'访客展会');
  const rest=await claimReceiptEmails(pool,10);assert.equal(rest.length,RECEIPT_EMAIL_DAILY_LIMIT_PER_RECIPIENT-2,'leased emails must not be claimed twice');
  await releaseReceiptEmails(pool,rest.map(email=>email.id));
  const reclaimed=await claimReceiptEmails(pool,10);
  assert.deepEqual(reclaimed.map(email=>[email.id,email.attempts]).sort(),rest.map(email=>[email.id,1]).sort(),'released emails are claimable again without spending an attempt');
  await completeReceiptEmail(pool,claimed[0]!.id);
  assert.equal(await failReceiptEmail(pool,claimed[1]!,'SMTP_EENVELOPE',true),true);
  const states=(await pool.query<{id:string;delivered:boolean;failed:boolean}>('SELECT id,delivered_at IS NOT NULL AS delivered,failed_at IS NOT NULL AS failed FROM project_receipt_emails WHERE id=ANY($1)',[[claimed[0]!.id,claimed[1]!.id]])).rows;
  assert.deepEqual(Object.fromEntries(states.map(row=>[row.id,[row.delivered,row.failed]])),{[claimed[0]!.id]:[true,false],[claimed[1]!.id]:[false,true]});
});
