import type { FastifyInstance } from 'fastify';
import type { Redis } from 'ioredis';
import type pg from 'pg';
import type { Config } from '../../config.js';
import { createStorage } from '../../infra/storage.js';
import { registerAuthentication } from '../authentication.js';
import { registerAdminAuthRoutes } from './auth/index.js';
import { registerAdminMeRoutes } from './me/index.js';
import { registerAdminUserRoutes } from './users.controller.js';
import { registerAdminSchemesRoutes } from './schemes/index.js';
import { registerAdminSchemeImportsRoutes } from './scheme-imports/index.js';
import { registerAdminAssetsRoutes } from './assets/index.js';
import { registerAdminBomRoutes } from './bill-of-materials/index.js';
import { registerAdminReviewsRoutes } from './reviews/index.js';
import { registerAdminDictionariesRoutes } from './dictionaries/index.js';
import { registerAdminAuditLogsRoutes } from './audit-logs/index.js';
import { registerAdminAiModelRoutes } from './ai-models/index.js';
import { registerAdminPromptTemplateRoutes } from './prompt-templates/index.js';
import { registerAdminProjectRoutes } from './projects/index.js';
import { registerAdminProjectNotificationRoutes } from './project-notifications/index.js';
import { registerAdminSchemeSearchesRoutes } from './scheme-searches/index.js';
import { registerAdminCreditRoutes } from './credits/index.js';
import { registerAdminGenerationJobRoutes } from './generation-jobs/index.js';
import { registerAdminAuthorization } from './authorization.js';
import { registerAdminRoleRoutes } from './roles.controller.js';
import { registerAdminDashboardRoutes } from './dashboard/index.js';

export async function registerAdminModule(app: FastifyInstance, config: Config, pool: pg.Pool, redis: Redis, storage: ReturnType<typeof createStorage>): Promise<void> {
  await app.register(async admin => {
    registerAuthentication(admin, pool, redis, 'admin');
    registerAdminAuthorization(admin);
    await registerAdminRoleRoutes(admin, config, pool);
    await registerAdminAuthRoutes(admin, config, pool, redis);
    await registerAdminMeRoutes(admin, config, pool, redis);
    await registerAdminDashboardRoutes(admin, pool);
    await registerAdminCreditRoutes(admin, pool, redis);
    await registerAdminUserRoutes(admin, pool);
    await registerAdminSchemesRoutes(admin, pool, redis);
    await registerAdminSchemeImportsRoutes(admin, pool, redis);
    await registerAdminAssetsRoutes(admin, pool, storage, redis);
    await registerAdminBomRoutes(admin, pool, storage, redis, config);
    await registerAdminReviewsRoutes(admin, pool, redis);
    await registerAdminDictionariesRoutes(admin, pool);
    await registerAdminAuditLogsRoutes(admin, pool);
    await registerAdminProjectRoutes(admin, pool, redis, storage);
    await registerAdminProjectNotificationRoutes(admin, pool);
    await registerAdminSchemeSearchesRoutes(admin, pool);
    await registerAdminAiModelRoutes(admin, pool, redis, config.aiModelEncryptionKey);
    await registerAdminPromptTemplateRoutes(admin, pool, redis);
    await registerAdminGenerationJobRoutes(admin, pool, storage, redis);
  }, { prefix: '/api/v1/admin' });
}
